name: food_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core : ^2.4.0
  firebase_auth : ^4.2.1
  firebase_database: ^10.0.9
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  colorful_safe_area: ^0.3.0
  shared_preferences: ^2.0.15
  after_layout: ^1.2.0
  introduction_screen: ^3.1.1
  email_validator: ^2.1.17
  url_launcher: ^6.1.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/vector/
    - assets/png/
    - assets/food/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Medium.ttf
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700

